<?php
/**
 * @file
 * Code for the ISB Site Feature feature.
 */

include_once 'isb_site_feature.features.inc';

/**
 * Implements hook_block_info().
 */
function isb_site_feature_block_info() {
  $blocks = array();
  $blocks['isb_login_link'] = array(
    'info' => t('Login link'),
  );
  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function isb_site_feature_block_view($delta='') {
  $block = array();

  switch($delta) {
    case 'isb_login_link' :
      if(!user_is_logged_in()) {
        $destination = drupal_get_destination();
        $block['content'] = l('Login', 'user', array(
          'query' => $destination['destination'] == 'home' ? '' : $destination,
          'attributes' => array('class' => array('nav-user')), 'html' => TRUE
        ));
      }
      break;
  }
  return $block;
}


/**
 * Implements hook_node_view_alter().
 */
function isb_site_feature_node_view_alter(&$build) {
  if(isset($build['book_navigation'])) {
    unset($build['book_navigation']);
  }
}

/**
 * Implements hook_default_panels_layout().
 */
function isb_site_feature_default_panels_layout() {
  $export = array();

  $layout = new stdClass();
  $layout->disabled = FALSE; /* Edit this to true to make a default layout disabled initially */
  $layout->api_version = 1;
  $layout->name = 'isb';
  $layout->admin_title = 'ISB responsive layout';
  $layout->admin_description = '';
  $layout->category = '';
  $layout->plugin = 'responsive';
  $layout->settings = array(
    'regions' => array(
      'header_a' => 'header_a',
      'header_b' => 'header_b',
      'header_c' => 'header_c',
      'subheader_a' => 'subheader_a',
      'subheader_b' => 'subheader_b',
      'subheader_c' => 'subheader_c',
      'navigation' => 'navigation',
      'title' => 'title',
      'sidebar_a' => 'sidebar_a',
      'body' => 'body',
      'sidebar_b' => 'sidebar_b',
      'footer_a' => 'footer_a',
      'footer_b' => 'footer_b',
      'footer_c' => 'footer_c',
    ),
    'overrides' => array(
      'smartphone' => array(),
      'tablet' => array(
        0 => array(
          'name' => 'header_a',
          'columns' => 2,
        ),
        1 => array(
          'name' => 'header_b',
          'columns' => 2,
        ),
        2 => array(
          'name' => 'header_c',
          'columns' => 2,
        ),
        3 => array(
          'name' => 'subheader_a',
          'columns' => 2,
        ),
        4 => array(
          'name' => 'subheader_b',
          'columns' => 2,
        ),
        5 => array(
          'name' => 'subheader_c',
          'columns' => 2,
        ),
        6 => array(
          'name' => 'body',
          'columns' => 4,
        ),
        7 => array(
          'name' => 'sidebar_a',
          'columns' => 1,
        ),
        8 => array(
          'name' => 'sidebar_b',
          'columns' => 1,
        ),
        9 => array(
          'name' => 'footer_a',
          'columns' => 2,
        ),
        10 => array(
          'name' => 'footer_b',
          'columns' => 2,
        ),
        11 => array(
          'name' => 'footer_c',
          'columns' => 2,
        ),
      ),
      'standard' => array(
        0 => array(
          'name' => 'header_a',
          'columns' => 6,
        ),
        1 => array(
          'name' => 'header_b',
          'columns' => 3,
        ),
        2 => array(
          'name' => 'header_c',
          'columns' => 3,
        ),
        3 => array(
          'name' => 'subheader_a',
          'columns' => 4,
        ),
        4 => array(
          'name' => 'subheader_b',
          'columns' => 4,
        ),
        5 => array(
          'name' => 'subheader_c',
          'columns' => 4,
        ),
        6 => array(
          'name' => 'body',
          'columns' => 7,
        ),
        7 => array(
          'name' => 'sidebar_a',
          'columns' => 3,
        ),
        8 => array(
          'name' => 'sidebar_b',
          'columns' => 2,
        ),
        9 => array(
          'name' => 'footer_a',
          'columns' => 4,
        ),
        10 => array(
          'name' => 'footer_b',
          'columns' => 4,
        ),
        11 => array(
          'name' => 'footer_c',
          'columns' => 4,
        ),
      ),
    ),
  );
  $export['isb'] = $layout;


  $layout = new stdClass();
  $layout->disabled = FALSE; /* Edit this to true to make a default layout disabled initially */
  $layout->api_version = 1;
  $layout->name = 'isb_no_sidebars';
  $layout->admin_title = 'ISB responsive wihout sidebars';
  $layout->admin_description = '';
  $layout->category = '';
  $layout->plugin = 'responsive';
  $layout->settings = array(
    'regions' => array(
      'header_a' => 'header_a',
      'header_b' => 'header_b',
      'header_c' => 'header_c',
      'subheader_a' => 'subheader_a',
      'subheader_b' => 'subheader_b',
      'subheader_c' => 'subheader_c',
      'body' => 'body',
      'footer_a' => 'footer_a',
      'footer_b' => 'footer_b',
      'footer_c' => 'footer_c',
    ),
    'overrides' => array(
      'smartphone' => array(),
      'tablet' => array(
        0 => array(
          'name' => 'header_a',
          'columns' => 2,
        ),
        1 => array(
          'name' => 'header_b',
          'columns' => 2,
        ),
        2 => array(
          'name' => 'header_c',
          'columns' => 2,
        ),
        3 => array(
          'name' => 'subheader_a',
          'columns' => 2,
        ),
        4 => array(
          'name' => 'subheader_b',
          'columns' => 2,
        ),
        5 => array(
          'name' => 'subheader_c',
          'columns' => 2,
        ),
        6 => array(
          'name' => 'body',
          'columns' => 6,
        ),
        7 => array(
          'name' => 'footer_a',
          'columns' => 2,
        ),
        8 => array(
          'name' => 'footer_b',
          'columns' => 2,
        ),
        9 => array(
          'name' => 'footer_c',
          'columns' => 2,
        ),
      ),
      'standard' => array(
        0 => array(
          'name' => 'header_a',
          'columns' => 6,
        ),
        1 => array(
          'name' => 'header_b',
          'columns' => 3,
        ),
        2 => array(
          'name' => 'header_c',
          'columns' => 3,
        ),
        3 => array(
          'name' => 'subheader_a',
          'columns' => 4,
        ),
        4 => array(
          'name' => 'subheader_b',
          'columns' => 4,
        ),
        5 => array(
          'name' => 'subheader_c',
          'columns' => 4,
        ),
        6 => array(
          'name' => 'body',
          'columns' => 12,
        ),
        7 => array(
          'name' => 'footer_a',
          'columns' => 4,
        ),
        8 => array(
          'name' => 'footer_b',
          'columns' => 4,
        ),
        9 => array(
          'name' => 'footer_c',
          'columns' => 4,
        ),
      ),
    ),
  );
  $export['isb_no_sidebars'] = $layout;

  return $export;
}

